token: <1420162191:AAH2dY-RMIJD0R_6hGYMZ3PaGwAa7dikDLs>

#seconds
max_download_time: 30

#minutes
max_video_duration: 60

#tgbotapi logger
debug: false

#custom logger
logging: true

bot_username: <@YourMusicUploaderBot>
